name: Build and upload python packages to Github release

on:
  workflow_dispatch

jobs:
  build-wheels-macos:
    runs-on: macos-10.15
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      MINICONDA_FILENAME: Miniconda3-latest-MacOSX-x86_64.sh

    steps:
    - uses: actions/checkout@v2

    - name: Download and install miniconda
      shell: bash
      run: |
        curl -L -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
        bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
        echo "::add-path::$HOME/miniconda3/bin"
        echo "::add-path::$HOME/miniconda3/Scripts"
        conda init

    - name: Download and build dependencies
      run: |
        eval "$(conda shell.bash hook)"
        conda create -n meson python=3.8
        conda activate meson
        conda install -y meson
        make download-build-static-deps
        conda deactivate
      env:
        CC: clang
        CXX: clang++

    - name: Build and upload packages
      run: |
        eval "$(conda shell.bash hook)"
        for VERSION in 3.6 3.7 3.8 3.9 3.10; do
          conda create -n py$VERSION python=$VERSION
          conda activate py$VERSION
          python setup.py build_ext bdist_wheel
          conda deactivate
        done
      env:
        CC: clang
        CXX: clang++

    - uses: actions/upload-artifact@v2
      with:
        name: macos-wheels
        path: dist/*.whl


  build-wheels-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build package and upload from docker
      run: |
        docker run --rm -v "${PWD}:/opt/fast-mosestokenizer" \
          -e TWINE_USERNAME=__token__ \
          -e TWINE_PASSWORD=${{ secrets.PYPI_TOKEN }} \
          ubuntu:16.04 /bin/bash /opt/fast-mosestokenizer/build-release-linux.sh

    - uses: actions/upload-artifact@v2
      with:
        name: linux-wheels
        path: dist/*.whl


  make-release:
    needs:
      - build-wheels-macos
      - build-wheels-linux
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: linux-wheels
          path: dist

      - uses: actions/download-artifact@v2
        with:
          name: macos-wheels
          path: dist

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./web-ext-artifacts/translatelocally.xpi
          asset_name: translatelocally.xpi
          asset_content_type: application/zip